# Generated by Django 4.1 on 2022-09-03 14:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="memory_image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Fotoğraf ekleyin"
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yazar",
            ),
        ),
        migrations.AlterField(
            model_name="memory", name="content", field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="memory",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Başlık"),
        ),
    ]
